export const FETCH_ALL_FRIENDS_PENDING = "FETCH_ALL_FRIENDS_PENDING";
export const FETCH_ALL_FRIENDS_SUCCESS = "FETCH_ALL_FRIENDS_PENDING";
export const FETCH_ALL_FRIENDS_FAILED = "FETCH_ALL_FRIENDS_FAILED";

export const FETCH_ONE_FRIENDS_PENDING = "FETCH_ONE_FRIENDS_PENDING";
export const FETCH_ONE_FRIENDS_SUCCESS = "FETCH_ONE_FRIENDS_PENDING";
export const FETCH_ONE_FRIENDS_FAILED = "FETCH_ONE_FRIENDS_FAILED";

export const FETCH_ADD_FRIENDS_PENDING = "FETCH_ADD_FRIENDS_PENDING";
export const FETCH_ADD_FRIENDS_SUCCESS = "FETCH_ADD_FRIENDS_PENDING";
export const FETCH_ADD_FRIENDS_FAILED = "FETCH_ADD_FRIENDS_FAILED";

export const FETCH_REMOVE_FRIENDS_PENDING = "FETCH_REMOVE_FRIENDS_PENDING";
export const FETCH_REMOVE_FRIENDS_SUCCESS = "FETCH_REMOVE_FRIENDS_PENDING";
export const FETCH_REMOVE_FRIENDS_FAILED = "FETCH_REMOVE_FRIENDS_FAILED";

export const BASE_URL = `http://localhost:8082/api/sosh/friend-requests`;
